import type { Activity, MarketNode, SystemsInsight } from "./types";
import { uid } from "./utils";

export const DEFAULT_NODES: MarketNode[] = [
  {
    id: "oregon-solar",
    name: "Oregon Solar Node",
    regionTag: "USA / NW",
    lat: 45.5231,
    lng: -122.6765,
    energyPrice: 0.08,
    gpuSupply: 82,
    renewablePct: 96,
    carbonScore: 8,
    workloadsActive: 62,
    efficiencyScore: 80,
  },
  {
    id: "vancouver-hydro",
    name: "Vancouver Hydro Exchange",
    regionTag: "CAN / BC",
    lat: 49.2827,
    lng: -123.1207,
    energyPrice: 0.09,
    gpuSupply: 48,
    renewablePct: 92,
    carbonScore: 9,
    workloadsActive: 38,
    efficiencyScore: 78,
  },
  {
    id: "silicon-valley-colo",
    name: "Silicon Valley Colo",
    regionTag: "USA / CA",
    lat: 37.3875,
    lng: -122.0575,
    energyPrice: 0.14,
    gpuSupply: 86,
    renewablePct: 58,
    carbonScore: 22,
    workloadsActive: 71,
    efficiencyScore: 66,
  },
  {
    id: "texas-grid",
    name: "Texas Compute Farm",
    regionTag: "USA / TX",
    lat: 32.7767,
    lng: -96.797,
    energyPrice: 0.05,
    gpuSupply: 68,
    renewablePct: 41,
    carbonScore: 32,
    workloadsActive: 49,
    efficiencyScore: 63,
  },
  {
    id: "virginia-ix",
    name: "Virginia IX Core",
    regionTag: "USA / VA",
    lat: 39.0438,
    lng: -77.4874,
    energyPrice: 0.12,
    gpuSupply: 79,
    renewablePct: 46,
    carbonScore: 29,
    workloadsActive: 64,
    efficiencyScore: 62,
  },
  {
    id: "frankfurt-dc",
    name: "Frankfurt DC Hub",
    regionTag: "DEU / FRA",
    lat: 50.1109,
    lng: 8.6821,
    energyPrice: 0.19,
    gpuSupply: 73,
    renewablePct: 55,
    carbonScore: 24,
    workloadsActive: 58,
    efficiencyScore: 69,
  },
  {
    id: "london-grid",
    name: "London Energy Desk",
    regionTag: "GBR / LDN",
    lat: 51.5072,
    lng: -0.1276,
    energyPrice: 0.21,
    gpuSupply: 62,
    renewablePct: 61,
    carbonScore: 18,
    workloadsActive: 52,
    efficiencyScore: 71,
  },
  {
    id: "tokyo-gpu",
    name: "Tokyo GPU Grid",
    regionTag: "JPN / Kanto",
    lat: 35.6762,
    lng: 139.6503,
    energyPrice: 0.11,
    gpuSupply: 74,
    renewablePct: 52,
    carbonScore: 27,
    workloadsActive: 55,
    efficiencyScore: 70,
  },
  {
    id: "seoul-edge",
    name: "Seoul Edge Compute",
    regionTag: "KOR / SEL",
    lat: 37.5665,
    lng: 126.978,
    energyPrice: 0.13,
    gpuSupply: 66,
    renewablePct: 39,
    carbonScore: 35,
    workloadsActive: 57,
    efficiencyScore: 65,
  },
  {
    id: "singapore-exchange",
    name: "Singapore Compute Exchange",
    regionTag: "SGP / SIN",
    lat: 1.3521,
    lng: 103.8198,
    energyPrice: 0.18,
    gpuSupply: 71,
    renewablePct: 22,
    carbonScore: 48,
    workloadsActive: 61,
    efficiencyScore: 60,
  },
  {
    id: "mumbai-thermal",
    name: "Mumbai Power & GPU",
    regionTag: "IND / BOM",
    lat: 19.076,
    lng: 72.8777,
    energyPrice: 0.10,
    gpuSupply: 58,
    renewablePct: 28,
    carbonScore: 54,
    workloadsActive: 63,
    efficiencyScore: 58,
  },
  {
    id: "iceland-green",
    name: "Iceland Green Cluster",
    regionTag: "ISL / Reykjavik",
    lat: 64.1466,
    lng: -21.9426,
    energyPrice: 0.07,
    gpuSupply: 54,
    renewablePct: 93,
    carbonScore: 10,
    workloadsActive: 44,
    efficiencyScore: 76,
  },
  {
    id: "oslo-wind",
    name: "Oslo Wind Clearing",
    regionTag: "NOR / OSL",
    lat: 59.9139,
    lng: 10.7522,
    energyPrice: 0.16,
    gpuSupply: 45,
    renewablePct: 88,
    carbonScore: 11,
    workloadsActive: 36,
    efficiencyScore: 77,
  },
  {
    id: "sao-paulo-colo",
    name: "São Paulo Colo",
    regionTag: "BRA / SAO",
    lat: -23.5505,
    lng: -46.6333,
    energyPrice: 0.09,
    gpuSupply: 52,
    renewablePct: 83,
    carbonScore: 16,
    workloadsActive: 47,
    efficiencyScore: 72,
  },
  {
    id: "johannesburg-solar",
    name: "Johannesburg Solar Desk",
    regionTag: "ZAF / JNB",
    lat: -26.2041,
    lng: 28.0473,
    energyPrice: 0.08,
    gpuSupply: 41,
    renewablePct: 34,
    carbonScore: 49,
    workloadsActive: 43,
    efficiencyScore: 57,
  },
  {
    id: "sydney-grid",
    name: "Sydney Grid Node",
    regionTag: "AUS / SYD",
    lat: -33.8688,
    lng: 151.2093,
    energyPrice: 0.17,
    gpuSupply: 49,
    renewablePct: 46,
    carbonScore: 33,
    workloadsActive: 46,
    efficiencyScore: 64,
  },
];

export const STEADY_HUMAN_ALLOCATION = 62;
export const STEADY_AGENT_ALLOCATION = 38;
export const CRISIS_HUMAN_ALLOCATION = 12;
export const CRISIS_AGENT_ALLOCATION = 88;

export function cloneDefaultNodes(): MarketNode[] {
  return DEFAULT_NODES.map((n) => ({ ...n }));
}

export function seedActivity(): Activity[] {
  const now = Date.now();
  return [
    {
      id: uid("evt"),
      at: now - 35_000,
      kind: "market",
      message: "Tape: BOT_12 rebalanced compute exposure into Iceland (lower carbon basis).",
      fromNodeId: "tokyo-gpu",
      toNodeId: "iceland-green",
    },
    {
      id: uid("evt"),
      at: now - 20_000,
      kind: "purchase",
      message: "Fill: BOT_7 bought 40 GPU-hours @ Oregon.",
      toNodeId: "oregon-solar",
    },
    {
      id: uid("evt"),
      at: now - 9_000,
      kind: "market",
      message: "News: regional energy basis widened +18% on demand shock.",
    },
  ];
}

export const SYSTEMS_INSIGHTS: SystemsInsight[] = [
  {
    id: "benefit",
    label: "Benefit",
    title: "Global efficiency gains",
    body: "AI dynamically optimizes unused infrastructure globally, reducing waste and improving efficiency.",
  },
  {
    id: "concern",
    label: "Concern",
    title: "Profit over stability",
    body: "Autonomous systems may prioritize profit over human stability when bidding for scarce resources.",
  },
  {
    id: "failure",
    label: "Failure scenario",
    title: "Regional grid overload",
    body: "AI agents overload regional power grids while optimizing for profit and compute efficiency.",
  },
  {
    id: "ethics",
    label: "Ethical question",
    title: "Who gets the grid?",
    body: "Should AI agents be allowed to compete with humans for critical infrastructure resources like electricity?",
  },
];
